POST http://localhost:3001/api/blogs/63860df7e0e485d595379e41/comments
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11c3RpIiwiaWQiOiI2MzY2YzZlZGY2ZDJhMzM2NjU2OWU5NjgiLCJpYXQiOjE2Njc2ODAwMjN9.xO4aOJ5wP6Yt7w1exSLk1XLGOonWvob79uk_NIuuh2g

{
    "content": "testbjggfhghg"
}