Delete http://localhost:3001/api/blogs/63665026d1577ab8a7801493
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJXaXRoVG9rZW4iLCJpZCI6IjYzNjY1OWQzMWFkY2MwMzgxMDMyMGI1NCIsImlhdCI6MTY2NzY1MzE2Mn0.CtHgiNYB2EUswyAqpcbA1AWaVXB_dgwHBLo_wxhTDPk
